# eda_analytical.py
import os
import pandas as pd

# ====================================================
#                  CONFIGURATION
# ====================================================

DATA_PATH = "../../data/cleaned/student_depression_cleaned.csv"

# Output folders (already generated by eda_basic.py)
PLOT_DIRS = {
    "numeric": "../outputs/numeric",
    "categorical": "../outputs/categorical",
    "heatmap": "../outputs/heatmap",
    "target": "../outputs/target"
}

# ====================================================
#                  LOAD DATA
# ====================================================

def load_data(path=DATA_PATH):
    """Load the cleaned dataset (may contain duplicates)."""
    df = pd.read_csv(path)
    return df

# ====================================================
#          DETECT COLUMN TYPES
# ====================================================

def detect_column_types(df, target="Depression"):
    """Identify numeric and categorical columns, excluding target."""
    numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
    if target in numeric_cols:
        numeric_cols.remove(target)

    categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
    return numeric_cols, categorical_cols

# ====================================================
#           NUMERIC ANALYSIS
# ====================================================

def numeric_summary(df, numeric_cols):
    """Compute descriptive statistics for numeric columns."""
    summary = df[numeric_cols].describe().T  # Transpose for easier reading
    summary["missing"] = df[numeric_cols].isnull().sum()
    summary["unique"] = df[numeric_cols].nunique()
    return summary

# ====================================================
#           CATEGORICAL ANALYSIS
# ====================================================

def categorical_summary(df, categorical_cols):
    """Compute value counts for categorical columns."""
    cat_summary = {}
    for col in categorical_cols:
        counts = df[col].value_counts()
        percentages = df[col].value_counts(normalize=True) * 100
        cat_summary[col] = pd.DataFrame({
            "Count": counts,
            "Percentage": percentages.round(2)
        })
    return cat_summary

# ====================================================
#           TARGET DISTRIBUTION
# ====================================================

def target_distribution(df, target="Depression"):
    counts = df[target].value_counts()
    percentages = df[target].value_counts(normalize=True) * 100
    target_df = pd.DataFrame({
        "Count": counts,
        "Percentage": percentages.round(2)
    })
    return target_df

# ====================================================
#             PRINT ANALYTICAL REPORT
# ====================================================

def print_report(df, target="Depression"):
    numeric_cols, categorical_cols = detect_column_types(df, target)

    print("\n--- ANALYTICAL REPORT ---\n")

    # Dataset overview
    print("Dataset shape:", df.shape)
    print("Numeric columns:", numeric_cols)
    print("Categorical columns:", categorical_cols)
    print("Target column:", target)

    # Target distribution
    print("\nTarget distribution:")
    print(target_distribution(df, target))
    print(f"Target plot: {os.path.join(PLOT_DIRS['target'], f'{target}_distribution.png')}")

    # Numeric summary
    print("\nNumeric columns summary:")
    num_summary = numeric_summary(df, numeric_cols)
    print(num_summary)
    print("\nNumeric plots reference:")
    for col in numeric_cols:
        print(f"- {col}: {os.path.join(PLOT_DIRS['numeric'], f'{col}_numeric_plots.png')}")

    # Categorical summary
    print("\nCategorical columns summary:")
    cat_summary = categorical_summary(df, categorical_cols)
    for col, table in cat_summary.items():
        print(f"\n{col} distribution:")
        print(table)
        print(f"Plot reference: {os.path.join(PLOT_DIRS['categorical'], f'{col}_categorical_plot.png')}")

    # Correlation heatmap
    print(f"\nCorrelation heatmap: {os.path.join(PLOT_DIRS['heatmap'], 'correlation_heatmap.png')}")


# ====================================================
#                  MAIN EXECUTION
# ====================================================

if __name__ == "__main__":
    # Load dataset
    df = load_data()

    # Generate report
    print_report(df)
